import React, { useEffect, useCallback, useState, useRef } from 'react';
import { createPortal } from 'react-dom';
import { CornerUpLeft, Copy, Trash2, Check } from 'lucide-react';
import { normalizeReaction } from '../../utils/reactionUtils';
import {
  DEFAULT_QUICK_EMOJIS,
  extractMessageText,
  copyTextToClipboard,
  canUserDeleteMessage,
  triggerHaptic
} from '../../utils/mobileActionSheetUtils.js';
import './MobileActionSheet.css';

export {
  DEFAULT_QUICK_EMOJIS,
  extractMessageText,
  copyTextToClipboard,
  canUserDeleteMessage
};

/**
 * MobileActionSheet component for Telegram-style bottom sheet context menu & reaction carousel.
 */
export default function MobileActionSheet({
  isOpen,
  msg: msgProp,
  message,
  activeChat,
  currentUser,
  emojis = [],
  onClose,
  onReply,
  setReplyingTo,
  onCopy,
  onDelete,
  deleteMessage,
  onReactionSelect,
  toggleReaction,
  isOutgoing,
  canDelete = undefined
}) {
  const [copied, setCopied] = useState(false);
  const copyTimerRef = useRef(null);
  const backdropPointerDownRef = useRef(false);

  const msg = message || msgProp;

  useEffect(() => {
    if (!isOpen) {
      backdropPointerDownRef.current = false;
      setCopied(false);
      if (copyTimerRef.current) clearTimeout(copyTimerRef.current);
      return undefined;
    }

    const handleKeyDown = (e) => {
      if (e.key === 'Escape') {
        onClose?.();
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => {
      window.removeEventListener('keydown', handleKeyDown);
      if (copyTimerRef.current) clearTimeout(copyTimerRef.current);
    };
  }, [isOpen, onClose]);

  const handleReactionClick = useCallback((emo) => {
    if (!msg) return;
    triggerHaptic(12);

    if (typeof onReactionSelect === 'function') {
      onReactionSelect(emo);
    } else if (typeof toggleReaction === 'function' && activeChat?.id) {
      toggleReaction(activeChat.id, msg.id, emo);
    }
    onClose?.();
  }, [activeChat?.id, msg, onReactionSelect, toggleReaction, onClose]);

  const handleReply = useCallback(() => {
    if (!msg) return;
    triggerHaptic(10);

    if (typeof onReply === 'function') {
      onReply(msg);
    } else if (typeof setReplyingTo === 'function') {
      setReplyingTo(msg);
    }
    onClose?.();
  }, [msg, onReply, setReplyingTo, onClose]);

  const handleCopyText = useCallback(async () => {
    if (!msg) return;
    const copyableText = extractMessageText(msg);
    if (!copyableText) return;

    const success = await copyTextToClipboard(copyableText);
    if (success) {
      setCopied(true);
      triggerHaptic(10);
      if (typeof onCopy === 'function') {
        onCopy(msg);
      }

      copyTimerRef.current = setTimeout(() => {
        onClose?.();
      }, 350);
    }
  }, [msg, onCopy, onClose]);

  const handleDelete = useCallback(() => {
    if (!msg) return;
    triggerHaptic(15);

    if (typeof onDelete === 'function') {
      onDelete(msg);
    } else if (typeof deleteMessage === 'function' && activeChat?.id) {
      deleteMessage(activeChat.id, msg.id);
    }
    onClose?.();
  }, [activeChat?.id, msg, onDelete, deleteMessage, onClose]);

  if (!isOpen || !msg) return null;

  const copyableText = extractMessageText(msg);
  const showDelete = canUserDeleteMessage(msg, currentUser, activeChat, canDelete, isOutgoing);

  const reactionList = emojis && emojis.length > 0
    ? emojis.slice(0, 8)
    : DEFAULT_QUICK_EMOJIS;

  const sheetContent = (
    <div
      className="mobile-action-sheet-backdrop"
      // Ignore the compatibility click generated by the opening tap. Dismiss after
      // a fresh backdrop click so its pointer release cannot activate the chat below.
      onPointerDown={(event) => {
        backdropPointerDownRef.current = event.target === event.currentTarget;
      }}
      onClick={(event) => {
        if (event.target === event.currentTarget && backdropPointerDownRef.current) {
          backdropPointerDownRef.current = false;
          onClose?.();
        }
      }}
      data-test="mobile-action-sheet-backdrop"
      role="dialog"
      aria-modal="true"
      aria-label="Действия с сообщением"
    >
      <div
        className="mobile-action-sheet"
        onClick={(e) => e.stopPropagation()}
        data-test="mobile-action-sheet"
      >
        {/* Quick Reaction Carousel */}
        <div className="mobile-sheet-reactions" role="toolbar" aria-label="Быстрые реакции">
          {reactionList.map((emo) => {
            const isActive = msg.reactions?.some((r) => {
              const norm = normalizeReaction(r);
              return (
                r.emoji === emo &&
                (norm.users.includes('current') ||
                  norm.users.includes('me') ||
                  (currentUser && norm.users.includes(currentUser.id)))
              );
            });

            return (
              <button
                key={emo}
                type="button"
                className={`mobile-sheet-reaction-pill ${isActive ? 'active' : ''}`}
                onClick={() => handleReactionClick(emo)}
                aria-label={`Реакция ${emo}`}
                data-test={`mobile-reaction-${emo}`}
              >
                {emo}
              </button>
            );
          })}
        </div>

        {/* Action Menu Items */}
        <div className="mobile-sheet-menu" role="menu">
          <button
            type="button"
            className="mobile-sheet-item"
            onClick={handleReply}
            data-test="mobile-action-reply"
            role="menuitem"
          >
            <div className="mobile-sheet-item-icon">
              <CornerUpLeft size={19} />
            </div>
            <span className="mobile-sheet-item-label">Ответить</span>
          </button>

          {Boolean(copyableText) && (
            <button
              type="button"
              className="mobile-sheet-item"
              onClick={handleCopyText}
              data-test="mobile-action-copy"
              role="menuitem"
            >
              <div className="mobile-sheet-item-icon">
                {copied ? <Check size={19} className="success-icon" /> : <Copy size={19} />}
              </div>
              <span className="mobile-sheet-item-label">
                {copied ? 'Скопировано!' : 'Копировать текст'}
              </span>
            </button>
          )}

          {showDelete && (
            <button
              type="button"
              className="mobile-sheet-item delete"
              onClick={handleDelete}
              data-test="mobile-action-delete"
              role="menuitem"
            >
              <div className="mobile-sheet-item-icon">
                <Trash2 size={19} />
              </div>
              <span className="mobile-sheet-item-label">Удалить</span>
            </button>
          )}
        </div>
      </div>
    </div>
  );

  if (typeof document !== 'undefined' && document.body) {
    return createPortal(sheetContent, document.body);
  }

  return sheetContent;
}
